version: '3.7'

services:
  backend:
    image: docker.pkg.github.com/esamarathon/omnibar-moderation/omnibar-moderation:latest-backend
    restart: always
    volumes:
      - ./backend/dist/state:/home/node/app/backend/dist/state
    ports:
      - 8081:8081
  frontend:
    image: docker.pkg.github.com/esamarathon/omnibar-moderation/omnibar-moderation:latest-frontend
    restart: always
    ports:
      - 8080:80
