FROM node:14-alpine as builder
WORKDIR /home/node/app
RUN mkdir -p ./backend && mkdir -p ./shared
COPY ./package*.json ./yarn.lock ./
COPY ./backend/package*.json ./backend/yarn.lock ./backend/
COPY ./shared/package*.json ./shared/yarn.lock ./shared/
RUN cd backend && yarn install && cd ../shared && yarn install
COPY . ./
RUN cd shared && yarn build && cd ../backend && yarn build

FROM node:14-alpine
WORKDIR /home/node/app
COPY --from=builder /home/node/app ./
EXPOSE 8080
CMD yarn start
