name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout this repository
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    # Copy settings from GitHub secrets to the file system so Docker can copy them
    - name: Copy settings from secrets to file system
      run: |
        echo "$SETTINGS_PROD" >> settings.prod.json
        echo "$SETTINGS_TEST" >> settings.test.json
      shell: bash
      env:
        SETTINGS_PROD: ${{ secrets['SETTINGS_PROD'] }}
        SETTINGS_TEST: ${{ secrets['SETTINGS_TEST'] }}

    # Setup Docker Buildx
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Login to the GitHub container registry
    - name: Login to GitHub container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push the Docker image for the backend to GitHub
    - name: Build and push Docker image for backend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.backend
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Build and push the "latest" Docker image for the frontend to GitHub
    - name: Build and push Docker image for frontend (latest)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.frontend
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILD_TARGET=prod

    # Build and push the "test" Docker image for the frontend to GitHub
    - name: Build and push Docker image for frontend (test)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.frontend
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/frontend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILD_TARGET=test
